default:
	g++ `pkg-config --cflags opencv` -o `basename vision.cpp .cpp` vision.cpp `pkg-config --libs opencv`
regr:
	g++ `pkg-config --cflags opencv` -o `basename regression.cpp .cpp` regression.cpp `pkg-config --libs opencv`

